# Netlify Configuration File

[build]
  # Command to run for building the site
  command = "npm run build:netlify"
  
  # Directory that contains the deploy-ready files
  publish = "dist/client"
  
  # Directory for serverless functions
  functions = "netlify/functions"

# Environment variables for build
[build.environment]
  NODE_VERSION = "20"

# SPA redirect rules - ensures client-side routing works
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API redirects - routes API calls to serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Development settings
[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 5173
  publish = "dist/client"
  autoLaunch = false